#!/bin/sh
uci set network.lan.ipv6=off
uci set network.wan.ipv6=off
uci set dhcp.lan.dhcpv6=disabled
uci set network.lan.ipaddr='192.168.16.1'
uci del network.lan.ifname

uci set wireless.@wifi-device[0].disabled=0
uci set wireless.@wifi-iface[0].disabled=0
uci set wireless.@wifi-iface[0].ssid='ot4g'
uci set wireless.@wifi-iface[0].key='12345678'
uci set wireless.@wifi-iface[0].encryption='psk2'
uci set wireless.sta.disabled=1
uci commit

uci set network.wanb=interface
uci set network.wanb.proto='qmi'
uci set network.wanb.device='/dev/cdc-wdm0'
uci set network.wanb.delegate='0'
uci set network.wanb.pdptype='ipv4'
uci set network.wanb.auth='none'
uci commit

uci add_list firewall.@zone[1].network='wanb'

uci set network.wan=interface
uci set network.wan.ifname='eth0'
uci set network.wan.proto='dhcp'
uci set network.wan.delegate='0'
uci add_list network.wan.dns='119.29.29.29'
uci commit

uci del mwan3.wan.track_ip
uci add_list mwan3.wan.track_ip='119.29.29.29'
uci add_list mwan3.wan.track_ip='223.5.5.5'
uci set mwan3.wanb.enabled='1'
uci del mwan3.wanb.track_ip
uci add_list mwan3.wanb.track_ip='119.29.29.29'
uci add_list mwan3.wanb.track_ip='223.5.5.5'
uci set mwan3.default_rule.use_policy='wan_wanb'
uci commit
